### ISSUE TITLE
Documentation: PostCode is no longer a standard validation class

### ISSUE THREAD

**Issue by Chealer** [zendframework/zend-validator#111]
According to [Standard Validation Classes](https://docs.zendframework.com/zend-validator/set/), PostCode comes with the zend-validator distribution. While this appears to be correct for Zend 2.0, this is no longer the case in zend-validator 2.8. PostCode is now shipped in zend-i18n (which zend-validator merely suggests).

Had I not been away from Zend for a long time, this would probably have been obvious since [the reference page for PostCode](https://docs.zendframework.com/zend-validator/validators/post-code/) uses the right namespace prefix.

Note that the zend-i18n reference does not mention PostCode (in other words, the page should be moved, not just deleted).

**Comment by froschdesign** [comment]
See:

- zendframework/zend-validator#121 
- zendframework/zend-i18n#59
