### ISSUE TITLE
CreditCard Validation - new number range needed

### ISSUE THREAD

**Issue by Mercury1987** [zendframework/zend-validator#118]
Hey,

on october 14th MasterCard will become a new BIN number range (222100 - 272099)

Please add the new range to the existing in $cardType (row 115)

`
/*Now*/
protected $cardType = array(
  .....
       
        self::MASTERCARD       => array('51', '52', '53', '54', '55'),

....        
    );
`

`
/*Needed*/
protected $cardType = array(
....        
        self::MASTERCARD       => array('51', '52', '53', '54', '55', '22', '23', '24', '25', '26', '27'),
....
    );
`

https://www.forte.net/blog/mastercard-bin-range-coming/

**Comment by zf2timo** [comment]
There is already a PR: see #110

**Comment by Mercury1987** [comment]
Oh :-)
sorry not seen
