### ISSUE TITLE
Zend\Validator\GreaterThan does not translate message template

### ISSUE THREAD

**Issue by fermius** [zendframework/zend-validator#134]
The message [NOT_GREATER_INCLUSIVE](https://github.com/zendframework/zend-validator/blob/master/src/GreaterThan.php#L27) is wrong defined accordingly to [ES translation](https://github.com/zendframework/zend-i18n-resources/blob/master/languages/es/Zend_Validate.php#L205) and others. The message would be

"The input is not greater or equal than '%min%'"

instead of 

"The input is not greater than or equal to '%min%'"

**Comment by froschdesign** [comment]
A fix is provided: zendframework/zend-i18n-resources#28

Thanks for reporting!
