### ISSUE TITLE
Zend\Validator\Hostname add supporting of *.shop TLD

### ISSUE THREAD

**Issue by oleksii-lisovyi** [zendframework/zend-validator#139]
Hello Guys,

While working with ZF1 on Magento 1.x I found, that some customers are not able to register account with email like example@my.shop.

Also I found, that this TLD is not present in the latest version of ZF2.
So can you please add TLD .shop as valid one to the related class?

Kind regards,

Oleksii Lisovyi

**Comment by Xerkus** [comment]
TLDs are updated from IANA and  generally become available with the next zend-validator release after IANA published them.
In this case it was  2.8.2
