### ISSUE TITLE
How to validate a dynamic form element

### ISSUE THREAD

**Issue by navin12** [zendframework/zend-validator#146]
I am trying to validate text only and required true a dynamic element array witch is created by JQuery and append to zend form but i am not able validate it...?

ex.
```
<input type='text' name='familymember[]' />
<input type='text' name='familymember[]' />
<input type='text' name='familymember[]' />
```

**Comment by Ocramius** [comment]
@navin12 you'd write a custom validator by implementing the [`ValidatorInterface`](https://github.com/zendframework/zend-validator/blob/99b528e01276054458da9553b587cfb959dfa436/src/ValidatorInterface.php). The accepted value would then be `?array` (considering no elements may have been submitted).

**Comment by froschdesign** [comment]
@navin12 
You can use [`zend-inputfilter`](https://docs.zendframework.com/zend-inputfilter/). A short example:

```php
$inputFilter = new \Zend\InputFilter\InputFilter();
$inputFilter->add(
    [
        'name'       => 'familymember',
        'type'       => \Zend\InputFilter\ArrayInput::class,
        'required'   => true,
        'filters'    => [
            [
                'name' => \Zend\Filter\StringTrim::class,
            ],
            [
                'name' => \Zend\Filter\StringTrim::class,
            ],
        ],
        'validators' => [
            [
                'name'    => \Zend\Validator\StringLength::class,
                'options' => [
                    'max' => 7,
                ],
            ],
        ],
    ]
);

$inputFilter->setData(
    [
        'familymember' => [
            'Mom',
            'Dad',
            'Brother',
            'Sister',
        ],
    ]
);

var_dump($inputFilter->isValid()); // true

$inputFilter->setData(
    [
        'familymember' => [
            'Neighbour',
        ],
    ]
);

var_dump($inputFilter->isValid()); // false
```

**Caution:** For an empty array you need a workaround.

```php
$inputFilter->setData(
    [
        'familymember' => [],
    ]
);

var_dump($inputFilter->isValid()); // true

if (array_key_exists('familymember', $data) || empty($data['familymember'])) {
    $data = [];
}

$inputFilter->setData($data);

var_dump($inputFilter->isValid()); // false

**Comment by navin12** [comment]
geting error :
**Input factory expects the "type" to be a valid class; received "\Zend\InputFilter\ArrayInput::class"**
i thing because of this line i mentioned in bold : 
$inputFilter->add(
    [
        'name'       => 'familymember',
        **'type'       => '\Zend\InputFilter\ArrayInput::class',**
        'required'   => true,
        'filters'    => [
            [
                'name' => '\Zend\Filter\StringTrim::class',
            ],
            
        ],
        'validators' => [
            [
                'name'    => '\Zend\Validator\StringLength::class',
                'options' => [
                    'max' => 7,
                ],
            ],
        ],
    ]
);

**Comment by weierophinney** [comment]
Remove the quotes around the entries using ::class notation; those are
constant values.
