### ISSUE TITLE
Zend\Math is required by Zend\Validator\Csrf but packae is not required

### ISSUE THREAD

**Issue by heiglandreas** [zendframework/zend-validator#147]
```Zend\Validator\Csrf``` requires the packages ```zend-session``` and ```zend-math``` but in composer.json they are only set as dev-requirements. Even though they are listed as suggestions, the package in itself is not usable without these packages. so they should be included in the ```require```-section.

**Comment by weierophinney** [comment]
All validators are opt -in, and the majority have no dependencies outside those in the "require" section. For this reason, we list any validator-specific deps as suggestions, but do not require them. 

Eventually, we may split these into separate packages so we can make those deps requirements, but for now, they are suggestions.

**Comment by heiglandreas** [comment]
Then the suggestions should at least include which validators can only be used when the suggested package is added…

**Comment by weierophinney** [comment]
Would you be willing to do a PR for that, or at least start one?

**Comment by heiglandreas** [comment]
Already at it 😉
