### ISSUE TITLE
Mimetype-Validation of Multiple Files broken

### ISSUE THREAD

**Issue by BlckStar** [zendframework/zend-validator#176]
https://github.com/zendframework/zend-validator/commit/3fc1e6614672eb7dbba816677c5a660a953bb563

This currently Breaks Mimetype-Validation of Multiple Files because it closes the finfo-handle after the first validation. 
At the second Validation the finfo-handle is closed and does not reopen at the setMagicFile-Function.

**Comment by werc** [comment]
Agree with @BlckStar. When "multiple" input has one file validation is ok. But when sending more than one files there is warning message:

`WARN (4): finfo_file(): supplied resource is not a valid file_info resource {"errno":2,"file":"....\\vendor\\zendframework\\zend-validator\\src\\File\\MimeType.php","line":387}`
