### ISSUE TITLE
[ZF3] Use PHP native validators?

### ISSUE THREAD

**Issue by bakura10** [zendframework/zend-validator#19]
Hi everyone,

As part of the upcoming refactor to ZF3 validator, I think we should discuss if we maintain our own implementation for some validators, or use the built-in validators included in PHP (http://php.net/manual/en/filter.filters.validate.php).

For the pros:

* Less work on our side and things to maintain, especially for maintenance
* Better performance as those complex validators
* Some validators have more options

For the cons:

* I know that some validators used to have some bug... but it was long time ago and maybe those have been fixed long time ago, especially as we set dependency to 5.5 now
* Some validators have less options

The impacted validators are:

* Email (https://github.com/zendframework/zend-validator/blob/master/src/EmailAddress.php)
* Float: (currently defined in Zend\I18n)
* Int
* Ip
* Url
* Regex

**Comment by Maks3w** [comment]
There is nothing to discuss here. If you refactor the internals of any class and tests keep working then it's ok. 

Note this does not imply a bc break so it can be done now

**Comment by bakura10** [comment]
Tests Will break because the validators does not offer the same option for modifying the behaviour of validation. For some validators the php ones offer more option and for some it offers less option.

Envoyé de mon iPhone

**Comment by Maks3w** [comment]
This must be discussed per validator and not as a global.

**Comment by akrabat** [comment]
As a general point, I would prefer to use `filter_var` wherever we can. As @Maks3w says, this need to be looked at on a case-by-case basis, but I'm in favour as long as we don't lose any important features.

**Comment by weierophinney** [comment]
One other aspect to consider: in some cases, our validators are more fine-grained than what PHP offers via ext/filter. In such cases, I'd expect we would want to keep our own behaviors.
