### ISSUE TITLE
Use of undefined constant INTL_IDNA_VARIANT_UTS46 in 2.10 release

### ISSUE THREAD

**Issue by onshop** [zendframework/zend-validator#192]
Using PHP 5.6.24:

/vendor/zendframework/zend-validator/src/EmailAddress.php:557 Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46'

In PHP 5.6.28 the constant is defined.

**Comment by xtreamwayz** [comment]
According to https://3v4l.org/elX65, the constant is available in PHP 5.4.0. I'm guessing the intl extension uses the ICU system lib and your server has a really old version of the ICU lib. Support for UTS #46 Unicode IDNA Compatibility Processing was added in ICU 4.6 and [released on 2010-12-02](http://site.icu-project.org/download/46).

**Comment by onshop** [comment]
Thank you for your assistance @xtreamwayz. We were running a very old ICU lib version.
