### ISSUE TITLE
Bug with the Step validator

### ISSUE THREAD

**Issue by biserantonov** [zendframework/zend-validator#215]
Step validator is not working properly. For example if I set `baseValue = 50` and `step = 0.01` then the validation fails for the value of `50.09`, which is perfectly valid. I think the problem is in the calculation of the `fmod`:

`$fmod = $this->fmod($value - $this->baseValue, $this->step);`

In this example `$value - $this->baseValue == 0.090000000000003` and then `$fmod == 3.41E-15`. Maybe it the fmod is rounded to the precision of the step the issue will be fixed.

I'm using PHP 5.6.33

**Comment by Ocramius** [comment]
Requires a test case

**Comment by codisart** [comment]
Hi @Ocramius and @froschdesign,

I added some unit tests to prove the bug [pull request](https://github.com/zendframework/zend-validator/pull/218)
You can see the [travis build](https://travis-ci.org/zendframework/zend-validator/builds/343024015?utm_source=github_status&utm_medium=notification)
