### ISSUE TITLE
update_hostname_validator.php error

### ISSUE THREAD

**Issue by inarli** [zendframework/zend-validator#216]
Hello,
**Zend** framework 2.4.6
**Php** : 5.6.32

I use Zend framework 2.4.6 and when running update_hostname_validator.php I get following errors;

Called Command:

`php vendor/zendframework/zendframework/bin/update_hostname_validator.php`

Errors:

`PHP Warning:  require(/vendor/zendframework/zendframework/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /vendor/zendframework/zendframework/bin/update_hostname_validator.php on line 13
`

**Comment by inarli** [comment]
When I added to bin list the command is running successfull:

vendor/zendframework/zendframework/composer.json

    "bin": [
        ...
        ...
        "bin/update_hostname_validator.php"
    ],

I do not know exactly how to proceed.

**Comment by froschdesign** [comment]
I do not know that the script in this version was already there?!

**Comment by froschdesign** [comment]
@inarli 
> When I added to bin list the command is running successfull:

Change never the scripts / files in directory `vendor`.

Btw. You must update your version 2.4. You missed some security fixes!

**Comment by inarli** [comment]
No I copied script from version 2.4.6.

**Comment by froschdesign** [comment]
The script is only for internal usage of this repository. It changes files of this component. If you do this on your local machine, then all updates will overwritten after a Composer update.
Therefore it is not present as command in `composer.json`.

**Comment by inarli** [comment]
@froschdesign Thank you for replies.
But how to update the list of hostnames? Email validator says that the .group extension is invalid.

**Comment by froschdesign** [comment]
Update the zend-validator component.

**Comment by inarli** [comment]
Thanks, We will update our ZF version.

**Comment by froschdesign** [comment]
Good choice. 👍 

For further questions please use the [forum](https://discourse.zendframework.com/) or the [chat](https://zendframework-slack.herokuapp.com). Thanks!
