### ISSUE TITLE
Composer install does not require zend-filter

### ISSUE THREAD

**Issue by delliriun** [zendframework/zend-validator#221]
Using **composer require zendframework/zend-validator** will not require zend-filter wich is a requirement for Zend\Validator\Digits.

**Comment by froschdesign** [comment]
It's already there. Look at the [suggest section](https://getcomposer.org/doc/04-schema.md#suggest):

https://github.com/zendframework/zend-validator/blob/87e743d11d49a157011a49a962c25e7a11adc7c5/composer.json#L34-L36

**Comment by delliriun** [comment]
Thank you Frank.
