### ISSUE TITLE
Missing requirement in composer.json

### ISSUE THREAD

**Issue by rkeet** [zendframework/zend-validator#222]
https://github.com/zendframework/zend-validator/blob/87e743d11d49a157011a49a962c25e7a11adc7c5/src/Csrf.php#L13

Module requires [module Zend Math](https://github.com/zendframework/zend-math). Module listed in composer.json as required under `require-dev`, not in `require` section ([see here](https://github.com/zendframework/zend-validator/blob/master/composer.json)). 

Can cause a `Class 'Zend\Math\Rand' not found` error.

Busy/late atm so do not have time to go fork/update/pr/whatever stuff; thought to report.

**Comment by froschdesign** [comment]
Is already included in the suggest section:

https://github.com/zendframework/zend-validator/blob/87e743d11d49a157011a49a962c25e7a11adc7c5/composer.json#L34-L38

Duplicate of #147 and #83

**Comment by rkeet** [comment]
As #83 was opened in 2016 and #147 halfway 2017 and the fact this has not been fixed, I would argue it would be better to make these requirements for now, until a separation into separate modules is done. 

Now you must go on a hunt to see what's going wrong because `Zend\Math` is not required/autoloaded.

**Comment by froschdesign** [comment]
> I would argue it would be better to make these requirements for now…

And then comes the next reporter, we should set the zend-math component as optional. 😉 

> …until a separation into separate modules is done.

1. There are already 163 components which need to be maintained.
2. zend-validator [will be revised](https://discourse.zendframework.com/t/rfc-new-validation-component/208).

---

The suggest section in a Composer file is for all packages they are _not strictly required_ and zend-math is only used in the CSRF validator.
