### ISSUE TITLE
Warning: A non-numeric value encountered

### ISSUE THREAD

**Issue by atan4o** [zendframework/zend-validator#225]
Hello,

Validating a form email address with a \Zend\Validator\EmailAddress or \Zend\Validator\Hostname triggers an warning and does not properly validates.

OS: Windows 10 64bit,
PHP:  PHP 7.1.8 (cli) (built: Aug  1 2017 21:10:31) ( NTS MSVC14 (Visual C++ 2015) x86 )

Code to reproduce:

```php
$filter->add(array(
            'name' => 'email',
            'required' => true,
            'filters' => array(
                array('name' => 'StringTrim')
            ),
            'validators' => array(
                array(
                    'name' => 'EmailAddress',
                    'options' => array(
                        'allow' => \Zend\Validator\EmailAddress::class,
                        'useMxCheck' => false
                    )
                ),
                array(
                    ........
                )
            )
        ));
```

Output:

> Warning: A non-numeric value encountered in D:\htdocs\project\vendor\zendframework\zend-validator\src\Hostname.php on line 2010
> 
> Warning: A non-numeric value encountered in D:\htdocs\project\vendor\zendframework\zend-validator\src\Hostname.php on line 2160
> 
> Warning: A non-numeric value encountered in D:\htdocs\project\vendor\zendframework\zend-validator\src\Hostname.php on line 2168
> 
> Warning: A non-numeric value encountered in D:\htdocs\project\vendor\zendframework\zend-validator\src\Hostname.php on line 2182

**Comment by froschdesign** [comment]
The warning is correct, because you are using a wrong value for the option `allow`.

```php
$validator = new Zend\Validator\EmailAddress(
    [
        'allow'      => \Zend\Validator\Hostname::ALLOW_ALL, // <-- See here!
        'useMxCheck' => false,
    ]
);

var_dump($validator->isValid('mail@example.com')); // true
```

Compare with the documentation and [the supported options](https://docs.zendframework.com/zend-validator/validators/email-address/#supported-options).

--- 

Please reduce your code example. Your problem is the validator. So there is no need to include zend-inputfilter and zend-filter. This will help us and we can help you much faster. Thanks!

**Comment by atan4o** [comment]
Thanks!
