### ISSUE TITLE
Zend_Validate_CreditCard return the valid type?

### ISSUE THREAD

**Issue by zerocarbthirty** [zendframework/zend-validator#258]
Hello, I have a question regarding the using of Zend_Validate_CreditCard.

Is there any way to make it return the type of card if it turns out to be valid?

**Comment by froschdesign** [comment]
@zerocarbthirty 
First: `Zend_Validate_CreditCard` doesn't belongs to this component. It's an old class from version 1 of Zend Framework.

> Is there any way to make it return the type of card if it turns out to be valid?

And the new validator `Zend\Validator\CreditCard` returns only `true` or `false`. You can not get the type of card.
