### ISSUE TITLE
Refactor ValidatorChainTest

### ISSUE THREAD

**Issue by Maks3w** [zendframework/zend-validator#27]
`ZendTest\Validator\ValidatorChainTest` has many tests are out of the scope of `ValidatorChain` these tests must be moved or removed.

Examples:
- testStaticFactoryClassNotFound
- testIsValidWithParameters
- testSetGetMessageLengthLimitation
- testSetGetDefaultTranslator

**Comment by adamlundrigan** [comment]
Is this issue still valid?
