### ISSUE TITLE
Automatize update of valid TLDs

### ISSUE THREAD

**Issue by Maks3w** [zendframework/zend-validator#3]
Actually Hostname validator depends of a regular execution of bin/update_hostname_validator.php for to host an up to date list of IANA TLDs

This should be automatized and even the list could be published in a different package for to allow more regular updates for LTS versions and newer.

Discussion: https://github.com/zendframework/zend-validator/pull/2

**Comment by fntlnz** [comment]
In discussion #2 @weierophinney  asked:
> And do what? Commit the changes from Travis? That seems risky...

What do you think about marking the build as failed if TLDs are not updated? This would highlight the necessity to update them in order to restore the green badge.

**Comment by Maks3w** [comment]
That was my suggestion. To execute the script and if git status is dirty then fail

**Comment by fntlnz** [comment]
mm.. ok I did not notice

**Comment by Maks3w** [comment]
@fntlnz Do you want to create a PR with a fix for this?

**Comment by fntlnz** [comment]
Yes, sounds good to me
