### ISSUE TITLE
[NotEmpty] validator strange behavior with boolean values

### ISSUE THREAD

**Issue by svycka** [zendframework/zend-validator#37]
I have json like this:
```json
{
    "name": "some name",
    "enabled": false
} 
```
And now I want to validate if enabled field is not empty.
```php
$validator = new NotEmpty();
$this->assertTrue($validator->isValid(false)); // fails
$validator->setType(NotEmpty::BOOLEAN);
$this->assertTrue($validator->isValid(false)); // fails, what? why? How can I check boolean values?
```
`false` it is for sure valid boolean value how this can be considered empty? and even when I set type to boolean this doesn't matter it is still empty. 

Even more strange this is in tests also https://github.com/zendframework/zend-validator/blob/c2dc846bbd278da7d6168295d685d5adfd8d7050/test/NotEmptyTest.php#L98

Maybe I don't know something and someone can explain reason behind this?

**Comment by Maks3w** [comment]
It's correct. You set BOOLEAN to be treat as empty.

Probably you want first to assert you will validate the correct value type. NotEmpty is not for this.

**Comment by svycka** [comment]
@Maks3w I use this with InputFilter and can't add notEmpty validator after type validation:
```php
public function testBoolean()
{
    $inputFilter = new InputFilter();
    $inputFilter->add([
        'name'       => 'enabled',
        'required'   => true,
        'validators' => [
            [
                'name'    => 'Zend\Validator\Callback',
                'options' => [
                    'callback' => function ($value) {
                        return is_bool($value);
                    },
                ],
            ],
        ],
    ]);
    $inputFilter->setData(['enabled' => false]);
    $this->assertTrue($inputFilter->isValid(false)); // fails
}
```
Can you show me how to do that in this situation?

**Comment by Maks3w** [comment]
Why do you need the NotEmpty validator. I think you don't need to assert that. Always you will have a value.

**Comment by svycka** [comment]
I want field to be required and only allow boolean. And for now InputFilter required works only with NotEmpty validator so I can't remove this. 

As I asked before can you show me example how would you do this: make enabled required and allow only boolean.

Even worse situation would be if I would need this field optional. I would set required false type validation would not be called at all in this situation. Then I would think maybe 'continue_if_empty' can help here but no then 'enabled' will become required. If I provide data without 'enabled' like `[]` now walidator will fail because null is not boolean.

Maybe I don't get what you say and example would help to understand.

**Comment by svycka** [comment]
To show what what I want created two tests:
```php
public function testBooleanRequired()
{
    $inputFilter = new InputFilter();
    $inputFilter->add([
        'name'       => 'enabled',
        'required'   => true,
        'validators' => [
            [
                'name'    => 'Zend\Validator\Callback',
                'options' => [
                    'callback' => function ($value) {
                        return is_bool($value);
                    },
                ],
            ],
        ],
    ]);

    $inputFilter->setData([]);
    $this->assertFalse($inputFilter->isValid());
    $inputFilter->setData(['enabled' => true]);
    $this->assertTrue($inputFilter->isValid());
    $inputFilter->setData(['enabled' => false]);
    $this->assertTrue($inputFilter->isValid());
}

public function testBooleanOptional()
{
    $inputFilter = new InputFilter();
    $inputFilter->add([
        'name'       => 'enabled',
        'required'   => false,
        //'continue_if_empty' => true,
        'validators' => [
            [
                'name'    => 'Zend\Validator\Callback',
                'options' => [
                    'callback' => function ($value) {
                        return is_bool($value);
                    },
                ],
            ],
        ],
    ]);

    $inputFilter->setData([]);
    $this->assertTrue($inputFilter->isValid());
    $inputFilter->setData(['enabled' => true]);
    $this->assertTrue($inputFilter->isValid());
    $inputFilter->setData(['enabled' => false]);
    $this->assertTrue($inputFilter->isValid());
}
```

@Maks3w can you show me how should I change inputFilter config to make them pass

**Comment by svycka** [comment]
After a bit of thinking I think required one would pass if when added `'continue_if_empty' => true` but  that's maybe a bit more like workaround than correct behavior? For second one can't find workaround.

**Comment by Maks3w** [comment]
1) Your issue is more like how InputFilter works than an issue with NonEmpty validator

2) For disable the injection of NonEmpty you can set `true` to `AllowEmpty` and `ContinueIfEmpty`

3) Optional fields is fixed in current master

Extra: AllowEmpty / ContinueIfEmpty will be deprecated since InputFilter 2.6. Silently fail on v3 and removed on v4.

**Comment by svycka** [comment]
ok I disagree with `false` to be empty but well if its ok with everyone else I give up. But for me and few more people this was confusing because when you say should be empty you don't expect that in context when you need boolean valid value like` false` could be considered empty. 

That's very similar with other issue where '0.0' was considered empty and '0' not, now I see this was fixed but about for 2 years this was considered valid behavior.

**Comment by Maks3w** [comment]
@svycka You can tune the behavior by setting a custom type.

**Comment by svycka** [comment]
I know that, just saying that not me alone saw this just after bug was discovered because this is not very intuitive. This validator is very confusing and i don't like it even more than date validator :)

**Comment by webrider** [comment]
To validate boolean on validator use like this

`$notEmpty = new \Zend\Validator\NotEmpty(\Zend\Validator\NotEmpty::NULL);
null -> invalid
false -> valid
true -> valid
`
