### ISSUE TITLE
Wrong return type in doc block of `ValidatorChain::getValidators()`

### ISSUE THREAD

**Issue by hoppithek** [zendframework/zend-validator#42]
`ValidatorChain::getValidators()` is documented to return a `\Zend\Stdlib\PriorityQueue` instance, but actually returns an `array`.
https://github.com/zendframework/zend-validator/blob/master/src/ValidatorChain.php#L283

This behavior also differs from the `\Zend\Filter\FilterChain::getFilters()` which does no conservion of the internal `PriorityQueue` to `array` before returning.

**Comment by Maks3w** [comment]
Could you send a pull request setting the return to ValidatorInterface[]?

I think the most important thing is a traversable group of validators.

**Comment by hoppithek** [comment]
I could do that, but `getValidators()` does not return a traversable group of `ValidatorInterface`. It returns an array structure like:
```
return [
    ['instance' => ValidatorInterface, 'breakChainOnFailure' => bool],
    ['instance' => ValidatorInterface, 'breakChainOnFailure' => bool],
    //...
];
```
which is traversable and contains `ValidatorInterface` instances, but is not usable as `foreach (ValidatorChain::getValidators() as $validator) { /*...*/} `.

If I should change the return type to `ValidatorInterface[]` anyways, just say so.

**Comment by Maks3w** [comment]
You're right. Then just `array` as you said at the begin
