### ISSUE TITLE
An alias "fileupload" was requested but no service could be found.

### ISSUE THREAD

**Issue by VadimIzmalkov** [zendframework/zend-validator#59]
While creating object of Http()
`$receiver = new \Zend\File\Transfer\Adapter\Http();`
get exception Zend\ServiceManager\Exception\ServiceNotFoundException:

> An alias "fileupload" was requested but no service could be found.

seems issue belongs to this package

**Comment by froschdesign** [comment]
Was fixed with version 2.6.0
