### ISSUE TITLE
Translations do not work with Zend\Mvc 3 anymore

### ISSUE THREAD

**Issue by RalfEggert** [zendframework/zend-validator#86]
I just stumbled upon an issue with `Zend\Validator` in combination with the `Zend\Mvc` 3 release. The 2.8.0 release is expecting a services called `MvcTranslator` to be injected as the translator for each validator.

https://github.com/zendframework/zend-validator/blob/master/src/ValidatorPluginManager.php#L446

But in `Zend\Mvc` 3 no service called `MvcTranslator` is defined anymore. This results into the fact that no validator messages are translated any more.

**Comment by RalfEggert** [comment]
I tried to add an alias for the `MvcTranslator` like this:

```
namespace Application;

use Zend\I18n\Translator\TranslatorInterface;

return [
    'service_manager' => [
        'aliases'            => array(
            'MvcTranslator' => TranslatorInterface::class,
        ),
    ],
];
```

But than I get this error: 

> Catchable fatal error: Argument 1 passed to Zend\Validator\AbstractValidator::setTranslator() must be an instance of Zend\Validator\Translator\TranslatorInterface, instance of Zend\I18n\Translator\Translator given

To solve this I could create a new class, extend the `Zend\I18n\Translator\Translator` and implement the `Zend\Validator\Translator\TranslatorInterface` and then overwrite the `Zend\I18n\Translator\TranslatorInterface` service with factory that instantiates my new class. But that is messy.

**Comment by weierophinney** [comment]
You need to install zendframework/zend-mvc-i18n, and register it as a module (if you use the component installer, you'll be prompted to do so). That module defined and registers these services now.

**Comment by RalfEggert** [comment]
:+1: 

Of course you are right. That solves the issue.
