### ISSUE TITLE
Maestro range 6772 didn't exist in src/CreditCard.php

### ISSUE THREAD

**Issue by dmitrijn** [zendframework/zend-validator#9]
hello, 

please add in src/CreditCard.php
line 113-114 new maestro bin range 6772 

        self::MAESTRO          => ['5018', '5020', '5038', '6304', '6759', '6761', '6762', '6763',
                                        '6764', '6765', '6766', '6772'],

**Comment by maegnes** [comment]
hi,
where did you get the information about the new range "6772" for maestro? couldn't find correlating information about that.
regards!

**Comment by dmitrijn** [comment]
@maegnes hi, 
i found it in bin database, you can check this range here http://www.binlist.net/ 677200-677299

**Comment by weierophinney** [comment]
Verified.
