### ISSUE TITLE
ImageSize and Size Validator behave unexpected in windows with PHP 5.4+

### ISSUE THREAD

**Issue by GeeH** [zendframework/zend-validator#96]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7650
User: @razonklnbd
Created On: 2015-12-06T03:12:39Z
Updated At: 2016-02-13T15:33:25Z
Body
Environment -
OS: Windows 10
PHP: 5.4+ [I tested in 5.4, 5.6 & 7.0]
ZF: 2.4.9

Recreate -
- create any HTML form to accept at least one image
- apply validator on size and image size
- submit form through http request

Reason -
at Zend\Validator\File\ImageSize and Zend\Validator\File\Size class isValid method return false due to using "stream_resolve_include_path" function. In my system it only resolves for include paths relative path document. You can locate exactly at line 354 of Zend\Validator\File\ImageSize class

---

**Comment by razonklnbd** [comment]
@GeeH Any update of this issue? OR can i make any suggestion to resolve?

**Comment by froschdesign** [comment]
@razonklnbd 
Suggestions or PRs are always welcome!

**Comment by razonklnbd** [comment]
we can replace line 354 to 357 with the following -
if(empty($file) || !is_readable($file)){
	if (empty($file) || false === stream_resolve_include_path($file)) {
		$this->error(self::NOT_READABLE);
		return false;
	}
}

we don't need to search into include path if we know file exists and readable

**Comment by froschdesign** [comment]
Duplicates #77 (See also this PR: #169)
